services:
  web:
    image: devchem/octo:bookstore_v{{web_version}}
    ports:
      - "3004:3004"
    environment:
      - VITE_BOOK_API_URL=http://www.abudarda.co.uk:8000

  api:
    image: devchem/octo:bookapi_v{{api_version}}
    ports:
      - "8000:8000"
    command: >
          sh -c "python manage.py wait_for_db &&
                 python manage.py migrate &&
                 python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - GOOGLE_OAUTH_APP_ID=${GOOGLE_OAUTH_APP_ID}
      - GOOGLE_OAUTH_APP_SECRET=${GOOGLE_OAUTH_APP_SECRET}
    depends_on:
      db:
        condition: service_healthy
    user: "user"  # Run the app service as the non-root user

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
