services:
  web:
    image: devchem/octo:bookstore_v{{web_version}}
    ports:
      - "3004:3004"
    environment:
      - VITE_BOOK_API_URL=http://api:8000

  api:
    image: devchem/octo:bookapi_v{{api_version}}
    ports:
      - "8000"
    command: >
          sh -c "python manage.py migrate &&
                 python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      - db
    user: "user"  # Run the app service as the non-root user

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
