# Generated by Django 3.1.1 on 2020-10-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('edition', models.CharField(max_length=50)),
                ('publication_year', models.IntegerField()),
                ('authors', models.ManyToManyField(to='core.Author')),
            ],
        ),
    ]
