# Generated by Django 5.1.7 on 2025-05-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(
                related_name='authors',
                related_query_name='Author.name',
                to='core.author'),
        ),
    ]
